services:
  frontend:
    build: ./frontend
    # ports:
      # - "5173:5173"
    restart: unless-stopped
    volumes:
      - ./frontend:/app # syncs the lxc code files (the ones i edit) with the files inside the container (for hot reload)
      - /app/node_modules
    environment:
      - VITE_HOSTS=${VITE_HOSTS}
      - VITE_HMR_HOST=${VITE_HMR_HOST}
      - VITE_HMR_PROTOCOL=${VITE_HMR_PROTOCOL}
      - VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
    depends_on:
      - backend
    
  backend:
    build: ./backend
    # ports:
      # - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./backend:/app # syncs the lxc code files (the ones i edit) with the files inside the container (for hot reload)
      - /app/node_modules
      - ./data:/app/database_files
    environment:
      - DB_PATH=/app/database_files/db.sqlite